### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [water-logger/MSYS2-Theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by water-logger** [comment]
Cool! I didn’t really expect ANYBODY to use my theme! Alright, will do.From: Joe BlockSent: Saturday, May 20, 2023 10:09 AMTo: water-logger/MSYS2-ThemeCc: SubscribedSubject: [water-logger/MSYS2-Theme] Please add a license file (Issue #2) I'd like to add this to awesome-zsh-plugins, but it doesn't have a license file.Please add a license file - if you don't have one in mind, I recommend using choosealicense.com to help choose an appropriate one.Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by water-logger** [comment]
Okay, I'll add a license.
